### Get all blogs
GET http://localhost:3001/api/blogs

### Create a blog
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MTdjNGEwZmEwZGQ1ZTBiOTM3MzMzZDUiLCJpYXQiOjE2MzU1MzgxNjl9.JXAXf1psmm57wHeeZ2kvNewvbVr585NZTG3Qns_ZyoM

{
    "title": "First blog",
    "author": "Donny Pratama",
    "url": "http://github.com/pratamatama",
    "likes": 999
}

### Delete a blog
DELETE http://localhost:3001/api/blogs/617c6fbe2173bb33fde91638
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MTdjNGEwZmEwZGQ1ZTBiOTM3MzMzZDUiLCJpYXQiOjE2MzU1MzgxNjl9.JXAXf1psmm57wHeeZ2kvNewvbVr585NZTG3Qns_ZyoM

### Update a blog
PUT http://localhost:3001/api/blogs/617c2c5c76d55b56044aef1c
Content-Type: application/json

{
    "title": "Updated blog",
    "author": "Donny Pratama",
    "url": "http://github.com/pratamatama",
    "likes": 1001
}

### Get all users
GET http://localhost:3001/api/users

### Login
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "password"
}

### Login (wrong password)
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "wrong"
}